package common

const (
	// HealthOK ...
	HealthOK string = "Health_OK"
	// HealthWarn ...
	HealthWarn string = "Health_Warn"
	// HealthError ...
	HealthError string = "Health_Err"
	// HealthUnknown ...
	HealthUnknown string = "Unknown"
)
