package common

const (
	// ProviderNameDoesNotSupport ...
	ProviderNameDoesNotSupport = "The ProviderName does not support currently, please select the other one"
	// MessageIDDoesNotExist ...
	MessageIDDoesNotExist = "The message ID does not exist in metadata storage"
	// MessageIDHasBeenDeleted ...
	MessageIDHasBeenDeleted = "The message ID has been deleted"
	// StatusCodeIsNotOK ...
	StatusCodeIsNotOK = "The status code of HTTP response is not 200"
)
